BOX_IMAGE = "jddiez/anscent7"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = "0.0.2"
    subconfig.vm.hostname = "master.jddr.lan"
    subconfig.vm.network "public_network", ip: "192.168.1.170"
    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
      v.name = "master"
    end
#    config.vm.provision "shell", inline: $script
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.hostname = "node-#{i}.jddr.lan"
      subconfig.vm.network "public_network", ip: "192.168.1.17#{i}"
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = "0.0.2"
      subconfig.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end
